import type { Course } from '../types'
import { section1 } from './01-platform-context'
import { section2 } from './02-dms-service'
import { section3 } from './03-full-load-and-cdc'
import { section4 } from './04-database-readiness'
import { section5 } from './05-dms-task-settings'
import { section6 } from './06-s3-target-settings'
import { section7 } from './07-bronze-acceptance'
import { section8 } from './08-manifest-example'
import { section9 } from './09-dms-verification'
import { section10 } from './10-cdc-recovery'
import { section11 } from './11-cdc-resume-example'
import { section12 } from './12-topics-and-contracts'
import { section13 } from './13-event-schema-example'
import { section14 } from './14-connector-to-bronze'
import { section15 } from './15-connector-settings-example'
import { section16 } from './16-event-time-and-hot-path'
import { section17 } from './17-spark-stream-example'
export const course: Course = { id: 'ingestion', title: 'Ingestion: batch, streaming, Bronze acceptance and recovery', sections: [section1, section2, section3, section4, section5, section6, section7, section8, section9, section10, section11, section12, section13, section14, section15, section16, section17] }
