import type { Course } from '../types'
import { section1 } from './01-dependency-graph'
import { section2 } from './02-dag-code-example'
import { section3 } from './03-quarantine-and-dlq'
import { section4 } from './04-data-health'
import { section5 } from './05-cloudwatch-example'
import { section6 } from './06-access-boundaries'
import { section7 } from './07-iam-policy-example'
import { section8 } from './08-audit-lineage'
import { section9 } from './09-cloudtrail-example'
import { section10 } from './10-environment-contract'
import { section11 } from './11-terraform-state-example'
import { section12 } from './12-release-pipeline'
import { section13 } from './13-ci-workflow-example'
import { section14 } from './14-rollback-and-cost'
import { section15 } from './15-schema-incident'
import { section16 } from './16-exception-ledger-example'
import { section17 } from './17-restart-and-backfill'
import { section18 } from './18-recovery-plan-example'
export const course: Course = { id: 'platform-operations', title: 'Platform operations: orchestration, controls, delivery and recovery', sections: [section1, section2, section3, section4, section5, section6, section7, section8, section9, section10, section11, section12, section13, section14, section15, section16, section17, section18] }
