import type { Course } from '../types'
import { section1 } from './01-landing-versus-tables'
import { section2 } from './02-schema-gate'
import { section3 } from './03-validation-and-exceptions'
import { section4 } from './04-validation-code-example'
import { section5 } from './05-cleansing-and-enrichment'
import { section6 } from './06-normalisation-code-example'
import { section7 } from './07-dedupe-and-change-order'
import { section8 } from './08-merge-code-example'
import { section9 } from './09-reporting-grain'
import { section10 } from './10-business-metrics'
import { section11 } from './11-gold-model-example'
import { section12 } from './12-reconciliation-and-release'
import { section13 } from './13-reconciliation-code-example'
export const course: Course = { id: 'transformation', title: 'Transformation: Bronze → Silver → Gold', sections: [section1, section2, section3, section4, section5, section6, section7, section8, section9, section10, section11, section12, section13] }
