# Confluent S3 plugin configuration fragment.
connector.class=io.confluent.connect.s3.S3SinkConnector
topics=meter.raw
tasks.max=3
s3.bucket.name=REPLACE_RAW_BUCKET
s3.region=eu-west-2
storage.class=io.confluent.connect.s3.storage.S3Storage
format.class=\
  io.confluent.connect.s3.format.avro.AvroFormat
partitioner.class=\
  io.confluent.connect.storage.partitioner.DefaultPartitioner
flush.size=10000
rotate.schedule.interval.ms=60000
timezone=UTC
s3.object.tagging=true
s3.ssea.name=aws:kms
s3.sse.kms.key.id=REPLACE_KEY_ARN
