import type { Course } from '../types'
import { section1 } from './01-lake-to-warehouse'
import { section2 } from './02-warehouse-load-example'
import { section3 } from './03-star-schema'
import { section4 } from './04-customer-scd2'
import { section5 } from './05-history-join-example'
import { section6 } from './06-analytics-and-science'
import { section7 } from './07-athena-snapshot-example'
import { section8 } from './08-ofgem-delivery'
import { section9 } from './09-delivery-state-example'
import { section10 } from './10-operational-lookups'
import { section11 } from './11-dynamodb-query-example'
export const course: Course = { id: 'consumption', title: 'Consumption: warehouse models and serving paths', sections: [section1, section2, section3, section4, section5, section6, section7, section8, section9, section10, section11] }
